export const TRAFFIC_START                    = 'TRAFFIC_START';
export const TRAFFIC_STOP                     = 'TRAFFIC_STOP';
export const TRAFFIC_TOGGLE                   = 'TRAFFIC_TOGGLE';

export const TOGGLE_ACTIVE_LIGHT_PAIR         = 'TOGGLE_ACTIVE_LIGHT_PAIR';

export const TURN_ACTIVE_LIGHT_PAIR_TO_RED    = 'TURN_ACTIVE_LIGHT_PAIR_TO_RED';
export const TURN_ACTIVE_LIGHT_PAIR_TO_ORANGE = 'TURN_ACTIVE_LIGHT_PAIR_TO_ORANGE';
export const TURN_ACTIVE_LIGHT_PAIR_TO_GREEN  = 'TURN_ACTIVE_LIGHT_PAIR_TO_GREEN';